/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author dabrin Raquel Solano
 */
public class Actualizar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnGuardar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jNombreViejo = new javax.swing.JLabel();
        jNuevoNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnGuardar.setBackground(new java.awt.Color(0, 51, 0));
        jbtnGuardar.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jbtnGuardar.setForeground(new java.awt.Color(204, 255, 204));
        jbtnGuardar.setText("Actualizar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jTextField1.setBackground(new java.awt.Color(0, 51, 0));
        jTextField1.setForeground(new java.awt.Color(204, 255, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, 40));

        jTextField2.setBackground(new java.awt.Color(0, 51, 0));
        jTextField2.setForeground(new java.awt.Color(204, 255, 204));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, 40));

        jNombreViejo.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jNombreViejo.setForeground(new java.awt.Color(204, 255, 204));
        jNombreViejo.setText("Ingrese el nombre del jugador que desea actualizar :");
        getContentPane().add(jNombreViejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jNuevoNombre.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jNuevoNombre.setForeground(new java.awt.Color(204, 255, 204));
        jNuevoNombre.setText("Ingrese datos nuevos:");
        getContentPane().add(jNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Boton guardar
 * @param evt 
 */
    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGuardarActionPerformed
/**
 * 
 * @param evt 
 */
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNombreViejo;
    private javax.swing.JLabel jNuevoNombre;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtnGuardar;
    // End of variables declaration//GEN-END:variables
}
