/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.JugadorArchivos;
import Logica.Jugar;
import Logica.manejadorNombres;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author dabri
 */
public class Borrar extends javax.swing.JInternalFrame {
    manejadorNombres mN=new manejadorNombres();
    /**
     * Creates new form Borrar
     */
    public Borrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNombre = new javax.swing.JLabel();
        jtfNombreBorrar = new javax.swing.JTextField();
        jbtnBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNombre.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jNombre.setForeground(new java.awt.Color(255, 102, 0));
        jNombre.setText("Ingrese el nombre que desea borrar:");
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jtfNombreBorrar.setBackground(new java.awt.Color(102, 0, 0));
        jtfNombreBorrar.setForeground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jtfNombreBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, -1));

        jbtnBorrar.setBackground(new java.awt.Color(102, 0, 0));
        jbtnBorrar.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        jbtnBorrar.setForeground(new java.awt.Color(255, 102, 0));
        jbtnBorrar.setText("BORRAR");
        jbtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondovPC.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt 
 */
    private void jbtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrarActionPerformed
        // TODO add your handling code here:    Jugar jugar = new Jugar();
        Jugar jugador = new Jugar();
        File f = new File("Nombres.txt");
        File fb = new File("NombresBorrados.txt");

        try {
            int c = 0;
            String linea = "";
            //BufferedWriter bw = new BufferedWriter(new FileWriter(f, true));
            BufferedReader br = new BufferedReader(new FileReader(f));
            String linea1 = "";
            int cont = 0;
            ArrayList<String> nombres = new ArrayList<String>();
            while (linea1 != null) {
                linea1 = br.readLine();
                if (jtfNombreBorrar.getText().equals(linea1)) {
                    nombres.add("*" + linea1);
                   cont++;

                } else {
                    nombres.add(linea1+"\n");
                }

            }

            if (cont == 0) {
                JOptionPane.showMessageDialog(null, "El nombre no existe");
            } else{
            JugadorArchivos archivos = new JugadorArchivos();
            archivos.borrar(nombres);
            }br.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error de acceso al archivo");
        }
    }//GEN-LAST:event_jbtnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNombre;
    private javax.swing.JButton jbtnBorrar;
    private javax.swing.JTextField jtfNombreBorrar;
    // End of variables declaration//GEN-END:variables
}
