/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dabri
 */
public class ListaJugadores extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaJugadores
     */
    public ListaJugadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnMostrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnMostrar.setBackground(new java.awt.Color(0, 51, 0));
        jbtnMostrar.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jbtnMostrar.setForeground(new java.awt.Color(204, 255, 204));
        jbtnMostrar.setText("Mostrar Jugadores");
        jbtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 143, 55));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/spade.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 130, 130));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param evt 
 */
    private void jbtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarActionPerformed
        // TODO add your handling code here:
        File f = new File("Nombres.txt");
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setNumRows(0);
        try {
            BufferedReader br = new BufferedReader(new FileReader(f));
            String linea = "";
            while ((linea = br.readLine()) != null) {
                Object[] e = new Object[1];
                e = linea.split(";");
                dtm.addRow(e);
            }
        } catch (FileNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "Archivo no existe");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error de acceso al archivo");
        }
    }//GEN-LAST:event_jbtnMostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnMostrar;
    // End of variables declaration//GEN-END:variables
}
