/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.Carta;
import Logica.Jugar;
import Logica.manejadorNombres;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Dabrin Najera , Raquel Badilla
 * @version 2.0
 */
public class PVIA extends javax.swing.JInternalFrame {

    java.util.Date fecha = new Date();
    Jugar jugar = new Jugar();

    int puntos1 = 0;
    int puntos2 = 0;
    String nom1;
    String nom2;
    manejadorNombres nombres = new manejadorNombres();

    /**
     * Creates new form PVIA
     */
    public PVIA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnReiniciar1 = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PuntosJ1 = new javax.swing.JTextField();
        Comenzar = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        PuntosJ2 = new javax.swing.JTextField();
        cartaj1 = new javax.swing.JButton();
        pasarJ1 = new javax.swing.JButton();
        QuedarseJ1 = new javax.swing.JButton();
        jNombre2 = new javax.swing.JLabel();
        jNombre1 = new javax.swing.JLabel();
        jLabelFondoGame = new javax.swing.JLabel();

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReiniciar1.setBackground(new java.awt.Color(0, 51, 0));
        jbtnReiniciar1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jbtnReiniciar1.setForeground(new java.awt.Color(204, 255, 204));
        jbtnReiniciar1.setText("Reniciar");
        jbtnReiniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReiniciar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReiniciar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 90, 30));

        jbtnNuevo.setBackground(new java.awt.Color(0, 51, 0));
        jbtnNuevo.setFont(new java.awt.Font("Gabriola", 0, 14)); // NOI18N
        jbtnNuevo.setForeground(new java.awt.Color(204, 255, 204));
        jbtnNuevo.setText("Juego Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 90, 30));

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 60, 80));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, 100));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 100));

        PuntosJ1.setBackground(new java.awt.Color(51, 102, 0));
        PuntosJ1.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        PuntosJ1.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(PuntosJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 60, -1));

        Comenzar.setBackground(new java.awt.Color(51, 0, 0));
        Comenzar.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        Comenzar.setForeground(new java.awt.Color(204, 255, 204));
        Comenzar.setText("COMENZAR");
        Comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(Comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 150, -1));

        finalizar.setBackground(new java.awt.Color(51, 0, 0));
        finalizar.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        finalizar.setForeground(new java.awt.Color(204, 255, 204));
        finalizar.setText("FINALIZAR");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        jPanel1.add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 150, -1));

        PuntosJ2.setBackground(new java.awt.Color(51, 102, 0));
        PuntosJ2.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        PuntosJ2.setForeground(new java.awt.Color(204, 255, 204));
        PuntosJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntosJ2ActionPerformed(evt);
            }
        });
        jPanel1.add(PuntosJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 60, -1));

        cartaj1.setBackground(new java.awt.Color(0, 51, 0));
        cartaj1.setFont(new java.awt.Font("Gabriola", 0, 24)); // NOI18N
        cartaj1.setForeground(new java.awt.Color(204, 255, 204));
        cartaj1.setText(" Tomar carta");
        cartaj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaj1ActionPerformed(evt);
            }
        });
        jPanel1.add(cartaj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 150, -1));

        pasarJ1.setBackground(new java.awt.Color(0, 51, 0));
        pasarJ1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        pasarJ1.setForeground(new java.awt.Color(204, 255, 204));
        pasarJ1.setText("Pasar");
        pasarJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasarJ1ActionPerformed(evt);
            }
        });
        jPanel1.add(pasarJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 70, -1));

        QuedarseJ1.setBackground(new java.awt.Color(0, 51, 0));
        QuedarseJ1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        QuedarseJ1.setForeground(new java.awt.Color(204, 255, 204));
        QuedarseJ1.setText("Quedarse");
        QuedarseJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuedarseJ1ActionPerformed(evt);
            }
        });
        jPanel1.add(QuedarseJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jNombre2.setBackground(new java.awt.Color(204, 255, 204));
        jNombre2.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jNombre2.setForeground(new java.awt.Color(204, 255, 204));
        jNombre2.setText("Jugador 2:");
        jPanel1.add(jNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 40));

        jNombre1.setFont(new java.awt.Font("Gabriola", 0, 18)); // NOI18N
        jNombre1.setForeground(new java.awt.Color(204, 255, 204));
        jNombre1.setText("Jugador 1:");
        jPanel1.add(jNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 380, 300));

        jLabelFondoGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondoGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     *
     * @param evt
     */
    private void ComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarActionPerformed
        // TODO add your handling code here:
        nombres.nombreJugador();
        nom1 = nombres.p1.getNombre();
        nom2 = nombres.p2.getNombre();
        cartaj1.setEnabled(true);
        pasarJ1.setEnabled(true);
        QuedarseJ1.setEnabled(true);
        JOptionPane.showMessageDialog(null, nombres.p1.getNombre());
        Comenzar.setVisible(false);
        Comenzar.setEnabled(false);
    }//GEN-LAST:event_ComenzarActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        // TODO add your handling code here:
        Jugar jugar = new Jugar();
        jugar.ganador(puntos1, puntos2, nom1, nom2);
    }//GEN-LAST:event_finalizarActionPerformed
    /**
     *
     * @param evt
     */
    private void PuntosJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntosJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PuntosJ2ActionPerformed
/**
 * 
 * @param evt 
 */
    private void cartaj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaj1ActionPerformed
        // TODO add your handling code here:
        Jugar jugar = new Jugar();
        Carta cartas = new Carta();
        QuedarseJ1.setEnabled(true);
        pasarJ1.setEnabled(true);

        jugar.llenarBaraja();
        int[] carta = jugar.seleccionarCarta();
        if (carta[0] == 1) {
            if (carta[1] == 2) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Picas.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 3) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Picas.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 4) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Picas.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 5) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Picas.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 6) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Picas.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 7) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Picas.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 8) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Picas.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 9) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Picas.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 10 || carta[1] == 1) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/APicas.jpg")));
                if (puntos1 >= 10) {
                    puntos1 = puntos1 + 1;
                } else {
                    puntos1 = puntos1 + 11;
                }
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 11) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JPicas.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 12) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QPicas.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 13) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KPicas.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            }
        }
        if (carta[0] == 2) {
            if (carta[1] == 2) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Trebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 3) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Trebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 4) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Trebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 5) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Trebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 6) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Trebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 7) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Trebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 8) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Trebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 9) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Trebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 10 || carta[1] == 1) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ATrebol.jpg")));
                if (puntos1 >= 10) {
                    puntos1 = puntos1 + 1;
                } else {
                    puntos1 = puntos1 + 11;
                }
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 11) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JTrebol.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 12) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QTrebol.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 10) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KTrebol.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            }
        }
        if (carta[0] == 3) {
            if (carta[1] == 2) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Diamond.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 3) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Diamond.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 4) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Diamond.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 5) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Diamond.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 6) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Diamond.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 7) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Diamond.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 8) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Diamond.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 9) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Diamond.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 10 || carta[1] == 1) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ADiamond.jpg")));
                if (puntos1 >= 10) {
                    puntos1 = puntos1 + 1;
                } else {
                    puntos1 = puntos1 + 11;
                }
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 11) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JDiamond.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 12) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QDiamond.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 13) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KDiamond.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            }
        }
        if (carta[0] == 4) {
            if (carta[1] == 2) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Corazon.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 3) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Corazon.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 4) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Corazon.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 5) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Corazon.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 6) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Corazon.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 7) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Corazon.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 8) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Corazon.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 9) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Corazon.jpg")));
                puntos1 = puntos1 + carta[1];
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 10 || carta[1] == 1) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ACorazon.jpg")));
                if (puntos1 >= 10) {
                    puntos1 = puntos1 + 1;
                } else {
                    puntos1 = puntos1 + 11;
                }
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 11) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JCorazon.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 12) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QCorazon.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            } else if (carta[1] == 13) {
                jLabel1.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KCorazon.jpg")));
                puntos1 = puntos1 + 10;
                PuntosJ1.setText("" + puntos1);
            }
        }
        if (puntos1 > 21 || puntos2 > 21) {

            cartaj1.setEnabled(false);

            QuedarseJ1.setEnabled(false);
            pasarJ1.setEnabled(false);

            finalizar.setEnabled(false);
            jugar.ganador(puntos1, puntos2, nom1, nom2);
        }

    }//GEN-LAST:event_cartaj1ActionPerformed
/**
 * 
 * @param evt 
 */
    private void pasarJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasarJ1ActionPerformed
        // TODO add your handling code here:

        QuedarseJ1.setEnabled(false);
        pasarJ1.setEnabled(false);
        pasarJ1.setEnabled(false);
        jugar.llenarBaraja();
        int[] carta = jugar.seleccionarCarta();
        boolean pc = true;
        while (pc) {
            if (carta[0] == 1) {
                if (carta[1] == 2) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 3) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 4) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 5) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 6) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 7) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 8) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 9) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10 || carta[1] == 1) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/APicas.jpg")));
                    if (puntos2 >= 10) {
                        puntos2 = puntos2 + 1;
                    } else {
                        puntos2 = puntos2 + 11;
                    }
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 11) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JPicas.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 12) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QPicas.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 13) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KPicas.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                }
            }
            if (carta[0] == 2) {
                if (carta[1] == 2) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 3) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 4) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 5) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 6) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 7) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 8) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 9) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10 || carta[1] == 1) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ATrebol.jpg")));
                    if (puntos2 >= 10) {
                        puntos2 = puntos2 + 1;
                    } else {
                        puntos2 = puntos2 + 11;
                    }
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 11) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JTrebol.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 12) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QTrebol.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KTrebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                }
            }
            if (carta[0] == 3) {
                if (carta[1] == 2) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 3) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 4) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 5) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 6) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 7) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 8) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 9) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10 || carta[1] == 1) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ADiamond.jpg")));
                    if (puntos2 >= 10) {
                        puntos2 = puntos2 + 1;
                    } else {
                        puntos2 = puntos2 + 11;
                    }
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 11) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JDiamond.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 12) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QDiamond.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 13) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KDiamond.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                }
            }
            if (carta[0] == 4) {
                if (carta[1] == 2) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 3) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 4) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 5) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 6) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 7) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Corazon.jpg")));
                    puntos2 = puntos1 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 8) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 9) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10 || carta[1] == 1) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ACorazon.jpg")));
                    if (puntos2 >= 10) {
                        puntos2 = puntos2 + 1;
                    } else {
                        puntos2 = puntos2 + 11;
                    }
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 11) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JCorazon.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 12) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QCorazon.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 13) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KCorazon.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                }
                if (puntos1 > 21 || puntos2 > 21) {

                    cartaj1.setEnabled(false);

                    QuedarseJ1.setEnabled(false);
                    pasarJ1.setEnabled(false);

                    finalizar.setEnabled(false);
                    jugar.ganador(puntos1, puntos2, nom1, nom2);

                }
            }
            if (puntos2 > 19) {
                QuedarseJ1.setEnabled(false);
                pasarJ1.setEnabled(false);
                finalizar.setEnabled(true);
                pc = false;
            }
        }
    }//GEN-LAST:event_pasarJ1ActionPerformed
/**
 * 
 * @param evt 
 */
    private void QuedarseJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuedarseJ1ActionPerformed
        // TODO add your handling code here:
        cartaj1.setEnabled(false);
        pasarJ1.setEnabled(false);
        QuedarseJ1.setEnabled(false);
        finalizar.setEnabled(true);
        jugar.llenarBaraja();
        int[] carta = jugar.seleccionarCarta();
        boolean pc = true;
        while (pc) {
            if (carta[0] == 1) {
                if (carta[1] == 2) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 3) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 4) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 5) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 6) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 7) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 8) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 9) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Picas.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10 || carta[1] == 1) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/APicas.jpg")));
                    if (puntos2 >= 10) {
                        puntos2 = puntos2 + 1;
                    } else {
                        puntos2 = puntos2 + 11;
                    }
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 11) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JPicas.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 12) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QPicas.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 13) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KPicas.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                }
            }
            if (carta[0] == 2) {
                if (carta[1] == 2) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 3) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 4) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 5) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 6) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 7) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 8) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 9) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Trebol.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10 || carta[1] == 1) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ATrebol.jpg")));
                    if (puntos2 >= 10) {
                        puntos2 = puntos2 + 1;
                    } else {
                        puntos2 = puntos2 + 11;
                    }
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 11) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JTrebol.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 12) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QTrebol.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 13) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KTrebol.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                }
            }
            if (carta[0] == 3) {
                if (carta[1] == 2) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 3) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 4) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 5) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 6) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 7) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 8) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 9) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Diamond.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10 || carta[1] == 1) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ADiamond.jpg")));
                    if (puntos2 >= 10) {
                        puntos2 = puntos2 + 1;
                    } else {
                        puntos2 = puntos2 + 11;
                    }
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 11) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JDiamond.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 12) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QDiamond.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 13) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KDiamond.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                }
            }
            if (carta[0] == 4) {
                if (carta[1] == 2) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/2Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 3) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/3Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 4) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/4Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 5) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/5Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 6) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/6Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 7) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/7Corazon.jpg")));
                    puntos2 = puntos1 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 8) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/8Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 9) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/9Corazon.jpg")));
                    puntos2 = puntos2 + carta[1];
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 10 || carta[1] == 1) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/ACorazon.jpg")));
                    if (puntos2 >= 10) {
                        puntos2 = puntos2 + 1;
                    } else {
                        puntos2 = puntos2 + 11;
                    }
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 11) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/JCorazon.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 12) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/QCorazon.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                } else if (carta[1] == 13) {
                    jLabel2.setIcon(new ImageIcon(ClassLoader.getSystemResource("Imagenes/KCorazon.jpg")));
                    puntos2 = puntos2 + 10;
                    PuntosJ2.setText("" + puntos2);
                }
                if (puntos1 > 21 || puntos2 > 21) {

                    cartaj1.setEnabled(false);

                    QuedarseJ1.setEnabled(false);
                    pasarJ1.setEnabled(false);

                    finalizar.setEnabled(false);
                    jugar.ganador(puntos1, puntos2, nom1, nom2);

                }
            }
            if (puntos2 > 19) {
                QuedarseJ1.setEnabled(false);
                pasarJ1.setEnabled(false);
                finalizar.setEnabled(true);
                pc = false;
            }

        }
    }//GEN-LAST:event_QuedarseJ1ActionPerformed

    private void jbtnReiniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReiniciar1ActionPerformed
        // TODO add your handling code here:
        puntos1 = 0;
        puntos2 = 0;
        QuedarseJ1.setEnabled(false);
        pasarJ1.setEnabled(false);
        finalizar.setEnabled(false);
        cartaj1.setEnabled(true);
        PuntosJ1.setText("");
        PuntosJ2.setText("");

    }//GEN-LAST:event_jbtnReiniciar1ActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        // TODO add your handling code here:
        puntos1 = 0;
        puntos2 = 0;
        nom1 = "";
        nom2 = "";
        nombres.nombreDeJugadores();  
        QuedarseJ1.setEnabled(false);
        pasarJ1.setEnabled(false);
        finalizar.setEnabled(false);
        cartaj1.setEnabled(false);
        Comenzar.setVisible(true);
        Comenzar.setEnabled(true);

    }//GEN-LAST:event_jbtnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Comenzar;
    private javax.swing.JTextField PuntosJ1;
    private javax.swing.JTextField PuntosJ2;
    public javax.swing.JButton QuedarseJ1;
    public javax.swing.JButton cartaj1;
    public javax.swing.JButton finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondoGame;
    private javax.swing.JLabel jNombre1;
    private javax.swing.JLabel jNombre2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JButton jbtnReiniciar1;
    public javax.swing.JButton pasarJ1;
    // End of variables declaration//GEN-END:variables
}
